apiVersion: v1
kind: Service
metadata:
  name: connection-tester-service
  labels:
    app: connection-tester
spec:
  type: NodePort
  selector:
    app: connection-tester
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      # NodePort will be automatically assigned between 30000-32767
      # Or you can specify: nodePort: 30080
